apiVersion: apps/v1
kind: Deployment
metadata:
  name: faysarah1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faysarah1
  template:
    metadata:
      labels:
        app: faysarah1
        group: faysarah
    spec:
      containers:
      - name: faysarah
        image: mcr.microsoft.com/dotnet/core/runtime:3.1-bionic-arm64v8
        imagePullPolicy: Always
